import Head from "next/head";
import "remixicon/fonts/remixicon.css";
import Layout from "../components/Layout";
import Dashboard from "../components/Dashboard";
export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontEnd Zone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     
        
          <Dashboard />
   
      
    </div>
  );
}
