import Head from "next/head";
import "remixicon/fonts/remixicon.css";
import Navbar from "../components/Navbar";
import MainSection from "../components/MainSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontEnd Zone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-primarybg h-screen w-full">
        <Navbar />
        <MainSection/>
      </main>
    </div>
  );
}
